
name: "JavaScript Build & Test [npm]"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to build and test Greenbone JavaScript Projects [npm]"
inputs:
  version:
    description: "Node version that should be installed"
    default: "16.x"
  token:
    description: "Token with GitHub Packages read rights required to install."
    required: true
    default: ${{ github.token }}
  cache-key:
    description: "Set the key to find the cached node modules"
    required: true
    default: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - run: echo "Install project [npm]"
      shell: bash
    - name: Install Project
      uses: greenbone/actions/install-npm@v2
      with:
        version: ${{ inputs.version }}
        token: ${{ inputs.token }}
        cache-key: ${{ inputs.cache-key }}
    - name: Build ...
      run: npm run build
      shell: bash
    - name: Run Testing
      run: npm run test:ci
      shell: bash
