name: "Python Package Linting"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to lint Greenbone Python packages"
inputs:
  packages:
    description: "Python packages to lint"
    required: true
  version:
    description: "Python version that should be installed"
    default: 3.9
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: greenbone/actions/poetry@v2
      with:
        version: ${{ inputs.version }}
    - run: echo "Running black"
      shell: bash
    - run: poetry run black --check --diff ${{ inputs.packages }}
      shell: bash
      name: Check with black
      working-directory: ${{ github.workspace }}
    - run: echo "Running pylint"
      shell: bash
    - run: poetry run pylint ${{ inputs.packages }}
      shell: bash
      name: Check with pylint
      working-directory: ${{ github.workspace }}
    - run: echo "Running pontos.version verify current"
      shell: bash
    - run: poetry run python -m pontos.version verify current
      shell: bash
      name: Check version information
      working-directory: ${{ github.workspace }}
