name: "Python Package Linting"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to lint Greenbone Python packages"

inputs:
  packages:
    description: "Python packages to lint"
    required: true
  version:
    description: "Python version that should be installed. Deprecated: Use `python-version` input instead."
    deprecationMessage: "version input is deprecated. Please use `python-version` input instead."
  python-version:
    description: "Python version that should be installed"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache:
    description: "Cache dependencies by setting it to 'true'. Leave unset or set to an other string then 'true' to disable the cache."
  cache-dependency-path:
    description: "Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies. Default is 'true'. Set to an other string then 'true' to disable the cache."
    default: "true"
  install-dependencies:
    description: "Install project dependencies. Default is 'true'. Set to an other string then 'true' to not install the dependencies."
    default: "true"
  working-directory:
    description: "Working directory where to run the action"
    default: ${{ github.workspace }}

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: greenbone/actions/poetry@v2
      with:
        version: ${{ inputs.version }}
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
        install-dependencies: ${{ inputs.install-dependencies }}
        working-directory: ${{ inputs.working-directory }}
    - run: echo "Running black"
      shell: bash
    - run: poetry run black --check --diff ${{ inputs.packages }}
      shell: bash
      name: Check with black
      working-directory: ${{ inputs.working-directory }}
    - run: echo "Running pylint"
      shell: bash
    - run: poetry run pylint ${{ inputs.packages }}
      shell: bash
      name: Check with pylint
      working-directory: ${{ inputs.working-directory }}
