name: "JavaScript Installer"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to install Greenbone JavaScript Projects"
inputs:
  version:
    description: "Node version that should be installed"
    default: "16.x"
  token:
    description: "Token with GitHub Packages read rights required to install."
    required: true
  cache-key:
    description: "Set the key to find the cached node modules"
    required: true
    default: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - run: echo "Checkout Repository"
      shell: bash
    - uses: actions/checkout@v3
    - name: Cache node modules
      shell: bash
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ inputs.cache-key }}
    - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
      name: List the state of node modules
      shell: bash
      continue-on-error: true
      run: npm list
    - name: Use Node.js ${{ inputs.version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}
        registry-url: 'https://npm.pkg.github.com'
    - run: npm ci
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
