name: "Container signing"
description: "Cosign based action to create container signatures. Depending on the input public/private key or keyless signatures are created."

inputs:
  image-digest:
    description: "Set the digest from the docker build and push action e.g the output of steps.build-and-push.outputs.digest."
    required: true
  image-tags:
    description: "Set the tags from the docker meta action e.g the output of steps.meta.outputs.tags."
    required: true
  cosign-key-password:
    description: "Set the cosign key password, if not set a keyless signature will be created."
    required: false
  cosign-key:
    description: "Set the cosign key, if not set a keyless signature will be created."
    required: false
  cosign-tlog-upload:
    description: "Turn on or turn off the cosign tlog upload function. Default: true"
    required: false
    default: "true"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: sigstore/cosign-installer@v3
    - name: Sign container image (public/private keypair)
      if: ${{ inputs.cosign-key-password && inputs.cosign-key }}
      shell: bash
      env:
        COSIGN_PASSWORD: ${{ inputs.cosign-key-password }}
        COSIGN_KEY: ${{ inputs.cosign-key }}
      run: |
        echo "${{ inputs.image-tags }}" | \
          xargs -I {} \
          cosign sign \
          --tlog-upload=${{ inputs.cosign-tlog-upload }} \
          -y \
          -r \
          --key env://COSIGN_KEY \
          {}@${{ inputs.image-digest }}
    - name: Sign the published Container Image (Keyless)
      if: ${{ !inputs.cosign-key-password || !inputs.cosign-key }}
      shell: bash
      run: |
        echo "${{ inputs.image-tags }}" | \
          xargs -I {} \
          cosign sign \
          --tlog-upload=${{ inputs.cosign-tlog-upload }} \
          -y \
          -r \
          {}@${{ inputs.image-digest }}
