name: "Container signing"
description: "Cosign based action to create container signatures. Depending on the input public/private key or keyless signatures are created."

inputs:
  image-tags:
    description: "Set the tags from the docker meta action e.g the output of steps.meta.outputs.tags."
    required: true
  cosign-key-password:
    description: "Set the cosign key password, if not set a keyless signature will be created."
    required: false
  cosign-key:
    description: "Set the cosign key, if not set a keyless signature will be created."
    required: false

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: sigstore/cosign-installer@v3
    - name: Sign container image (public/private keypair)
      if: ${{ inputs.cosign-key-password && inputs.cosign-key }}
      shell: bash
      env:
        COSIGN_PASSWORD: ${{ inputs.cosign-key-password }}
        COSIGN_KEY: ${{ inputs.cosign-key }}
      run: |
        echo "${{ inputs.image-tags }}" | \
          xargs -I {} cosign sign --recursive --key env://COSIGN_KEY {}
    - name: Sign the published Container Image (Keyless)
      if: ${{ !inputs.cosign-key-password || !inputs.cosign-key }}
      shell: bash
      run: |
        echo "${{ inputs.image-tags }}" | \
          xargs -I {} cosign sign --recursive {}
