name: "Greenbone Pull Request Backport Action"
description: "GitHub Action to backport Pull Requests"
author: "Björn Ricks"
inputs:
  config:
    description: "TOML config file to use"
    default: "backport.toml"
  token:
    description: "GitHub Token for authentication"
    default: ${{ github.token }}
  username:
    description: "GitHub user name to use for the backported commits. By default github.actor is used."
    default: ${{ github.actor }}
  python-version:
    description: "Python version to use for running the action"
    default: "3.10"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies. Default is 'true'. Set to an other string then 'true' to disable the cache."
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@62ad2c65d4d5e59b7e6608a4267a41c03ccb3cfd # v3.27.22
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        working-directory: ${{ github.action_path }}
        without-dev: "true"
        cache-dependency-path: ${{ github.action_path }}/poetry.lock
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
    - name: Run backport changes
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        poetry run backport-pull-request \
          --token ${{ inputs.token }} \
          --username ${{ inputs.username }} \
          --config-file ${{ inputs.config }}
