name: "Greenbone Pull Request Backport Action"
description: "GitHub Action to backport Pull Requests"
author: "Björn Ricks"
inputs:
  config:
    description: "TOML config file to use"
    default: "backport.toml"
  token:
    description: "GitHub Token for authentication"
    required: true
  username:
    description: "GitHub user name to use for the backported commits. By default github.actor is used."
  python-version:
    description: "Python version to use for running the action"
    required: false
    default: "3.10"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."

runs:
  using: "composite"
  steps:
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@v2
      with:
        version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        working-directory: ${{ github.action_path }}
        without-dev: "true"
        cache-dependency-path: ${{ github.action_path }}/poetry.lock
    - name: Run backport changes
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        poetry run backport-pull-request \
          --token ${{ inputs.token }} \
          --username ${{ inputs.username }} \
          --config-file ${{ inputs.config }}
