[project]
name = "backport-pull-request-action"
version = "1.0.0"
description = "A GitHub Action to backport Pull Requests"
authors = [{ name = "Björn Ricks", email = "bjoern.ricks@greenbone.net" }]
requires-python = ">=3.10,<4"
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "tomli>=1.0",
    "pontos>=23.2.2",
    "httpx2>=2.13.0",
]

[project.scripts]
backport-pull-request = "action.backport:main"

[dependency-groups]
dev = ["autohooks>=21.7.0", "autohooks-plugin-ruff>=21.6.0"]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["action"]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 80
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I", "PLE", "PLW"]


[tool.autohooks]
mode = "uv"
pre-commit = ["autohooks.plugins.ruff.check", "autohooks.plugins.ruff.format"]
