name: "Admin bypass action"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action that allows or disallows admin bypassing branch protection rules on the target branch."

inputs:
  github-token:
    description: "GitHub Token for authentication"
    default: ${{ github.token }}
  allow:
    description: "Allow or not? (Options: true, false)? Default: false"
    default: "false"
  repository:
    description: "What repository branch should be able to be bypassed by admins? Defaults to the executing repository."
    default: ${{ github.repository }}
  branch:
    description: "Target branch for the bypass. Default: main"
    default: "main"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: python
      with:
        python-version: "3.10"
    - name: Virtual Environment
      id: virtualenv
      run: |
        echo "path=${{ github.action_path }}/${{ github.action }}-venv" >> $GITHUB_OUTPUT
        echo "name=${{ github.action }}-venv" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache Virtual Environment
      id: cache-virtualenv
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ steps.virtualenv.outputs.name }}
        path: ${{ steps.virtualenv.outputs.path }}
    - name: Create virtual environment
      if: ${{ steps.cache-virtualenv.outputs.cache-hit != 'true' }}
      run: |
        python -m venv ${{ steps.virtualenv.outputs.path }}
      shell: bash
    - name: Install pontos
      run: |
        source ${{ steps.virtualenv.outputs.path }}/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade pontos
        wget https://github.com/greenbone/pontos/raw/main/scripts/github/enforce-admins.py -O ~/enforce-admins.py
      shell: bash
    - name: allow/not allow bypass?
      run: |
        if [[ "${{inputs.allow}}" == "true" ]];
        then
          echo "ALLOW_OPT=--allow" >> $GITHUB_ENV
        elif [[ "${{inputs.allow}}" == "false" ]];
        then
          echo "ALLOW_OPT=--no-allow" >> $GITHUB_ENV
        else
          echo "ALLOW_OPT=--no-allow" >> $GITHUB_ENV
        fi
      shell: bash
      # in case of blubber input let the branch be unlocked!
    - name: Prepare release and store the version
      run: |
        source ${{ steps.virtualenv.outputs.path }}/bin/activate
        pontos-github-script ~/enforce-admins.py ${{ inputs.repository }} ${{ inputs.branch }} ${{ env.ALLOW_OPT }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
