version: 2
updates:
    # GitHub Actions
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      time: "04:00"
#    commit-message:
#      prefix: "Deps"
#    groups:
#      dependencies:
#        patterns:
#          - "*"
  - package-ecosystem: "github-actions"
    # HINT: generate the list of directories apart from / with this command:
    # for dir in $(ls -d *| grep -v -E "README.md|LICENSE" | sort); do echo "      - \"$dir\""; done
    directories:
#      - "**/*"
      - "/"
      - "admin-bypass"
#      - "awx-run"
#      - "backport-pull-request"
#      - "checkout"
#      - "check-version"
#      - "container-build-push-generic"
#      - "container-multi-arch-manifest"
#      - "container-signing"
#      - "conventional-commits"
#      - "coverage-js"
#      - "coverage-python"
#      - "dependency-review"
#      - "deploy-env"
#      - "doc-coverage-clang"
#      - "download-artifact"
#      - "git-use-https-for-github"
#      - "hashsums"
#      - "helm-build-push"
      - "helm-login"
#      - "helm-version-upgrade"
#      - "install-cgreen"
#      - "install-node"
#      - "is-latest-tag"
#      - "lint-golang"
#      - "lint-node"
#      - "lint-python"
#      - "lock-branch"
#      - "mattermost-notify"
#      - "mypy-python"
#      - "npm-build-push"
#      - "oci-info"
#      - "pipx"
#      - "poetry"
#      - "pr-conventional-commit-labeler"
#      - "push-and-sign-artifact"
#      - "pypi-upload"
#      - "release"
#      - "release-assets"
#      - "release-assets_tests"
#      - "release-type"
#      - "release-version"
#      - "sbom-upload"
#      - "scp"
#      - "set-github-user"
#      - "setup-pontos"
#      - "signature"
#      - "sign-release-files"
#      - "ssh-known-hosts"
#      - "ssh-run-cmd"
#      - "test-node"
#      - "trigger-workflow"
#      - "update-header"
#      - "uv"
    schedule:
      interval: "weekly"
      time: "04:00"
    commit-message:
      prefix: "Deps"
#    groups:
#      dependencies:
#        patterns:
#          - "*"

    # PIP
  - package-ecosystem: pip
    directories:
      - "/backport-pull-request/"
      - "/conventional-commits/"
      - "/download-artifact/"
      - "/helm-version-upgrade/"
      - "/trigger-workflow/"
      - "/oci-info/"
      - "/pr-conventional-commit-labeler/"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"
    groups:
      dependencies:
        patterns:
          - "*"
