version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/poetry/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/release/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/release-python/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/coverage-python/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/lint-python/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/mypy-python/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/mattermost-notify/"
    schedule:
      interval: "weekly"
  - package-ecosystem: pip
    directory: "/trigger-workflow/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: pip
    directory: "/download-artifact/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: pip
    directory: "/backport-pull-request/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
