version: 2
updates:
    # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/poetry/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/release/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/release-python/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/coverage-python/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/lint-python/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/mypy-python/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/mattermost-notify/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/install-npm/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/lint-javascript/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/test-javascript/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"


    # PIP
  - package-ecosystem: pip
    directory: "/backport-pull-request/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"

  - package-ecosystem: pip
    directory: "/conventional-commits/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"

  - package-ecosystem: pip
    directory: "/download-artifact/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"

  - package-ecosystem: pip
    directory: "/helm-version-upgrade/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"

  - package-ecosystem: pip
    directory: "/trigger-workflow/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"
groups:
  dependencies:
  - patterns: "*"
