name: "Helm chart version upgrade"
description: "GitHub Action to upgrade a Helm chart version"
inputs:
  chart-path:
    description: "Full path to helm chart folder"
    required: true
  chart-version:
    description: "New helm chart version"
    required: true
  app-version:
    description: "New helm chart appVersion, optional default chart-version"
    required: false
  image-tag:
    description: "New helm chart docker image tag, optional default chart-version"
    required: false
  git-user:
    description: "Git user name for commit, set only if autocommit is desired"
    required: false
  git-user-email:
    description: "Git user email for commit, set only if autocommit is desired"
    required: false
  token:
    description: "Github token for commit, set only if autocommit is desired"
    required: false
  python-version:
    description: "Python version to use for running the action"
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@v2
      with:
        version: ${{ inputs.python-version }}
        working-directory: ${{ github.action_path }}
        without-dev: "true"
    - name: Run helm-chart-version-upgrade
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        cmd="--chart-path ${{ inputs.chart-path }} --chart-version ${{ inputs.chart-version }}"
        if [ "${{ inputs.app-version }}" ]; then
          cmd+=" --app-version ${{ inputs.app-version }}"
        fi
        if [ "${{ inputs.image-tag }}" ]; then
          cmd+=" --image-tag ${{ inputs.image-tag }}"
        fi
        poetry run helm-chart-version-upgrade $cmd
    - name: Push
      if: inputs.git-user && inputs.git-user-email && inputs.token
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        git config --global user.name "${{ inputs.git-user }}"
        git config --global user.email "${{ inputs.git-user-email }}"
        git add -u
        git commit -m "Change: Upgrade helm chart to version ${{ inputs.chart-version }}"
        git push
