[project]
name = "release-assets"
version = "0.1.0"
description = "Manage release assets"
authors = [{ name = "Greenbone", email = "info@greenbone.net" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "AGPL-3.0-or-later"
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python :: 3",
]
dependencies = ["pontos>=22.10.0"]

[project.scripts]
release-assets = "action.main:main"

[dependency-groups]
dev = [
  "autohooks-plugin-ruff>=23.10.0",
  "autohooks-plugin-mypy>=23.10.0",
  "coverage>=7.2.7",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["action"]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[tool.autohooks]
mode = "uv"
pre-commit = [
  "autohooks.plugins.ruff.check",
  "autohooks.plugins.ruff.format",
  "autohooks.plugins.mypy",
]

[tool.pontos.version]
version-module-file = "action/__version__.py"

[tool.ruff]
line-length = 80
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I", "PLE", "PLW"]

[tool.mypy]
files = "action"
ignore_missing_imports = true
explicit_package_bases = true

[tool.coverage.run]
branch = true
omit = ["tests/*", "*/__init__.py"]
source = ["action"]
