name: Container build and push ghcr.io
description: Container build and push action for ghcr.io.

inputs:
  build-context:
    description: "Path to image build context. Defualt is ."
    default: .
  build-docker-file:
    description: "Path to the docker file. Default is ./Dockerfile"
    default: ./Dockerfile
  build-args:
    description: "Use these build-args for the docker build process. Default is empty"
    default: ""
  build-secrets:
    description: "Use these build-secrets for the docker build process. Default is empty"
    default: ""
  cosign-key:
    description: "cosign key to sign the image. Default is empty"
    default: ""
  cosign-key-password:
    description: "cosign key password. Default is empty"
    default: ""
  image-labels:
    description: "Image labels."
    required: true
  image-url:
    description: "Image url/name without registry."
    required: true
  image-tags:
    description: "Image tags."
    required: true
  image-platforms:
    description: "Image platforms to build for. Default is linux/amd64"
    default: linux/amd64
  registry-password:
    description: "Registry password."
    required: true
  scout-user:
    description: "Dockerhub user for docker scout. Default is empty"
    default: ""
  scout-password:
    description: "Dockerhub user password for docker scout. Default is empty"
    default: ""


outputs:
  digest:
    description: "The container digest."
    value: ${{ steps.build-and-push.outputs.digest }}

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
  - name: Container build and push ghcr.io
    id: build-and-push
    uses: greenbone/actions/container-build-push-generic@v3
    with:
      build-context: ${{ inputs.build-context }}
      build-docker-file: ${{ inputs.build-docker-file }}
      build-args: ${{ inputs.build-args }}
      build-secrets: ${{ inputs.build-secrets }}
      cosign-key: ${{ inputs.cosign-key }}
      cosign-key-password: ${{ inputs.cosign-key-password }}
      image-url: ${{ inputs.image-url }}
      image-labels: ${{ inputs.image-labels }}
      image-tags: ${{ inputs.image-tags }}
      image-platforms: ${{ inputs.image-platforms }}
      registry: "ghcr.io"
      registry-password: ${{ inputs.registry-password }}
      scout-user: ${{ inputs.scout-user }}
      scout-password: ${{ inputs.scout-password }}
