name: "Dependency Review"
description: "Scans your pull requests for dependency changes"
branding:
  icon: "umbrella"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: "Dependency Review"
      uses: actions/dependency-review-action@56339e523c0409420f6c2c9a2f4292bbb3c07dd3 # v4.8.0
      with:
        fail-on-severity: high
        comment-summary-in-pr: true
        vulnerability-check: true
        license-check: true
        allow-licenses: |
          0BSD,
          AGPL-3.0-or-later,
          Apache-2.0,
          BlueOak-1.0.0,
          BSD-2-Clause,
          BSD-3-Clause-Clear,
          BSD-3-Clause,
          BSL-1.0,
          CAL-1.0,
          CC-BY-3.0,
          CC-BY-4.0,
          CC-BY-SA-4.0,
          CC0-1.0,
          EPL-2.0,
          GPL-1.0-or-later,
          GPL-2.0-only,
          GPL-2.0-or-later,
          GPL-2.0,
          GPL-3.0-only,
          GPL-3.0-or-later,
          GPL-3.0,
          ISC,
          LGPL-2.0-only,
          LGPL-2.0-or-later,
          LGPL-2.1-only,
          LGPL-2.1-or-later,
          LGPL-2.1,
          LGPL-3.0-only,
          LGPL-3.0,
          LGPL-3.0-or-later,
          MIT,
          MIT-CMU,
          MPL-1.1,
          MPL-2.0,
          OFL-1.1,
          PSF-2.0,
          Python-2.0,
          Python-2.0.1,
          Unicode-3.0,
          Unicode-DFS-2016,
          Unlicense,
          Zlib,
          ZPL-2.1

# Only single licenses are allowed in this list.
# A combination of licenses like `License-A AND License-B`
# is not supported. See:
# https://github.com/actions/dependency-review-action/issues/792
