name: "Dependency Review"
description: "Scans your pull requests for dependency changes"
branding:
  icon: "umbrella"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: "Dependency Review"
      uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a # v4.4.0
      with:
        fail-on-severity: high
        comment-summary-in-pr: true
        vulnerability-check: true
        license-check: true
        allow-licenses: |
          0BSD,
          AGPL-3.0-or-later,
          Apache-2.0,
          BlueOak-1.0.0,
          BSD-2-Clause,
          BSD-3-Clause-Clear,
          BSD-3-Clause,
          BSL-1.0,
          CAL-1.0,
          CC-BY-3.0,
          CC-BY-4.0,
          CC-BY-SA-4.0,
          CC0-1.0,
          EPL-2.0,
          GPL-2.0-only,
          GPL-2.0-or-later,
          GPL-2.0,
          GPL-3.0-or-later,
          ISC,
          LGPL-2.0-only,
          LGPL-2.0-or-later,
          LGPL-2.1-only,
          LGPL-2.1-or-later,
          LGPL-2.1,
          LGPL-3.0-only,
          LGPL-3.0,
          LGPL-3.0-or-later,
          MIT,
          MPL-1.1,
          MPL-2.0,
          OFL-1.1,
          PSF-2.0,
          Python-2.0,
          Python-2.0.1,
          Unicode-3.0,
          Unicode-DFS-2016,
          Unlicense

# Only single licenses are allowed in this list.
# A combination of licenses like `License-A AND License-B`
# is not supported. See:
# https://github.com/actions/dependency-review-action/issues/792
