name: "Dependency Review"
description: "Scans your pull requests for dependency changes"
branding:
  icon: "umbrella"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4
    - name: "Dependency Review"
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        comment-summary-in-pr: true
        vulnerability-check: true
        license-check: true
        allow-licenses: |
          0BSD,
          AGPL-3.0-or-later,
          GPL-3.0-or-later,
          LGPL-2.1,
          EPL-2.0,
          Python-2.0,
          GPL-2.0-or-later,
          GPL-2.0-only,
          LGPL-2.1-only,
          LGPL-3.0,
          LGPL-3.0-only,
          GPL-2.0,
          LGPL-2.1-or-later,
          MIT,
          ISC,
          Unlicense,
          Apache-2.0,
          BSD-3-Clause,
          BSD-2-Clause,
          MPL-2.0,
          CC-BY-4.0,
          CC-BY-3.0,
          CC-BY-SA-4.0,
          CC0-1.0,
          BSD-3-Clause-Clear,
          Unicode-DFS-2016,
          OFL-1.1,
          BlueOak-1.0.0,
          BSL-1.0,
          Python-2.0.1,
          PSF-2.0,
          LGPL-2.0-only,
          CAL-1.0
# Only single licenses are allowed in this list. 
# A combination of licenses like `License-A AND License-B` 
# is not supported. See:
# https://github.com/actions/dependency-review-action/issues/792
