name: "Validate Helm Chart"
description: "GitHub Action to validate a Helm chart using Helm template"
inputs:
  chart-path:
    description: "Path to the Helm chart to validate"
    required: true
  chart-name:
    description: "Chart to validate"
    required: true
  registry:
    description: "Registry name. Default: ghcr.io"
    default: "ghcr.io"
  registry-user:
    description: "Registry login user."
    required: true
  registry-token:
    description: "Registry login password/token."
    required: true
  chart-values-path:
    description: "Optional path to values.yaml file"
    required: false
    default: ""
  repository-url:
    description: "URL of the repository to clone (optional)"
    required: false
  repository-branch:
    description: "Branch of the repository to clone (optional)"
    required: false
  additional-chart-values-path:
    description: "Path to the additional values.yaml file within the cloned repository (optional)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Git credentials 
      uses: greenbone/actions/set-github-user@v3

    - name: Clone Additional Repository
      if: inputs.repository-url && inputs.repository-branch
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository-url }}
        path: additional-repo
        ref: ${{ inputs.repository-branch }}

    - name: Helm registry login 
      shell: bash
      run: |
        helm registry login \
          -u '${{ inputs.registry-user }}' \
          -p '${{ inputs.registry-token }}' \
          '${{ inputs.registry }}'

    - name: Check Helm Chart
      id: test-helm-chart
      shell: bash
      run: |
        HELM_COMMAND="helm template test ${{ inputs.chart-path }}/${{ inputs.chart-name }} --debug"
        
        # Include additional chart values from the cloned repository if provided
        if [ -n "${{ inputs.additional-chart-values-path }}" ]; then
          HELM_COMMAND="$HELM_COMMAND -f additional-repo/${{ inputs.additional-chart-values-path }}"
        fi

        # Include chart values path if provided
        if [ -n "${{ inputs.chart-values-path }}" ]; then
          HELM_COMMAND="$HELM_COMMAND -f ${{ inputs.chart-values-path }}"
        fi

        $HELM_COMMAND
