name: "Sign Windows Binary"
description: |
  "An action to sign Windows binaries."
inputs:
  file:
    description: "The file to sign with signtool.exe"
    required: true
  signing-certificate:
    description: "The certificate for signing the file"
    required: true
  signing-certificate-hash-alg:
    description: "The hash algorithm used for the signing-certificate"
    default: "sha512"
    required: false
  signing-password:
    description: "The password for the signing certificate"
    required: true
  timestamp-url:
    description: "The url of the timestamp server"
    required: true
  timestamp-hash-alg:
    description: "The hash algorithm used for the timestamp server"
    default: "sha512"
    required: false

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Sign file
      run: |
        signtool.exe sign /a /f ${{ inputs.signing-certificate }} /fd ${{ inputs.signing-certificate-hash-alg }} /p ${{ inputs.password }} /tr ${{ inputs.timestamp-url }} /td ${{ inputs.timestamp-hash-alg }} ${{ inputs.file }}

    - name: Verify Signing
      run: |
        signtool.exe verify /v /pa ${{ inputs.file }}
