name: "Sign Windows Binary"
description: |
  "An action to sign Windows binaries."
inputs:
  #repository:
  #  description: "GitHub repository (owner/name) to download the release files from."
  #  default: ${{ github.repository }}

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      repository: greenbone/techop-gvm-tools-signing

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install pipenv
      run: pip install pipenv --user
      # Do we need to set the PATH?

    - name: Setting up a pipenv
      run: |
        set PIPENV_pipenv_IN_PROJECT="true"
        pipenv install
        pipenv update
        build_and_sign.bat

    - name: Verify Signing
      run: |
        signtool.exe verify /v /pa Cli\gvm-cli.exe
        signtool.exe verify /v /pa Shell\gvm-pyshell.exe

    #- uses: skymatic/code-sign-action@v1
    #  with:
    #    certificate: '${{ secrets.CERTIFICATE }}'
    #    password: '${{ secrets.PASSWORD }}'
    #    certificatesha1: '${{ secrets.CERTHASH }}'
    #    certificatename: '${{ secrets.CERTNAME }}'
    #    description: 'My App'
    #    timestampUrl: 'http://timestamp.digicert.com'
    #    folder: 'files'
    #    recursive: true
