name: "Python Mypy Action"
author: "Tom Ricciuti <tom.ricciuti@greenbone.net>"
description: "An action that verifies python type hints by using mypy"

inputs:
  packages:
    description: "Python packages to check with mypy"
    required: true
  version:
    description: "Python version that should be installed"
    default: "3.9"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache:
    description: "Cache dependencies by setting it to 'true'. Leave unset or set to an other string then 'true' to disable the cache."
  cache-dependency-path:
    description: "Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies."

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: greenbone/actions/poetry@main
      with:
        version: ${{ inputs.version }}
        poetry-version: ${{ inputs.poetry-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - run: echo "Running mypy"
      shell: bash
    - run: poetry run mypy ${{ inputs.packages }}
      shell: bash
      name: Check with mypy
      working-directory: ${{ github.workspace }}
