name: "Python Mypy Action"
author: "Tom Ricciuti <tom.ricciuti@greenbone.net>"
description: "An action that verifies python type hints by using mypy"

inputs:
  packages:
    description: "Python packages to check with mypy"
    deprecationMessage: "packages input is deprecated. Please use `mypy-arguments` input instead."
    required: true
  version:
    description: "Python version that should be installed. Deprecated: Use `python-version` input instead."
    deprecationMessage: "version input is deprecated. Please use `python-version` input instead."
  mypy-arguments:
    description: "Additional arguments for running mypy"
    default: ""
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache:
    description: "Cache dependencies by setting it to 'true'. Leave unset or set to an other string then 'true' to disable the cache."
  cache-dependency-path:
    description: "Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies. Default is 'true'. Set to an other string then 'true' to disable the cache."
    default: "true"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: greenbone/actions/poetry@v2
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
    - run: poetry run mypy ${{ inputs.mypy-arguments }} ${{ inputs.packages }}
      shell: bash
      name: Check with mypy
      working-directory: ${{ github.workspace }}
