name: "Update File headers to the new year"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action that updates header year in all files of given directories."

inputs:
  github-user:
    description: "Github user name."
    required: true
  github-user-mail:
    description: "Mail address for the given github user."
    required: true
  github-user-token:
    description: "Token with write rights required to create the release."
    required: true
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
    required: false
  target:
    description: "Branch that should be released. Default: main"
    default: "main"
    required: false
  directories:
    description: "Specify the directories that should be updated, separated by space e.g. 'foo bar baz'"
    required: true
  exclude-file:
    description: "Specify the file, that contains files to ignore"
    default: .pontos-header-ignore
    required: false
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ env.FETCH_DEPTH }}
        ref: ${{ inputs.target }}
    - name: Set up pontos
      uses: greenbone/actions/setup-pontos@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set git name, mail and origin
      run: |
        git config --global user.name "${{ inputs.github-user }}"
        git config --global user.email "${{ inputs.github-user-mail }}"
        git remote set-url origin https://${{ inputs.github-user-token }}@github.com/${{ github.repository }}
      shell: bash
    - name: Store Branch name
      shell: bash
      run: |
        echo "HEAD=devops/update-header-$(date +"%Y")" >> $GITHUB_ENV
        echo "YEAR=$(date +"%Y")" >> $GITHUB_ENV
    - name: Run commands to update headers
      run: |
        git checkout -b ${{ env.HEAD }}
        pontos-update-header -d ${{ inputs.directories }}
      shell: bash
    - name: Run git commands for PR
      run: |
        git add -u
        git commit -m "Update header to ${{ env.YEAR }}"
        git push --set-upstream origin ${{ env.HEAD }}
        pontos-github pr ${{ github.repository }} ${{ env.HEAD }} ${{ inputs.target }} \
          'Update year to ${{ env.YEAR }} in copyright header' \
          --body "**What**:\n\nUpdate year to ${{ env.YEAR }} in \
          copyright header in all relevant files\n\n**Why**:* Files \
          should be up-to-date and we don't want to do it manually \
          in all projects\n\n**How**:\n\n* Automated process \
          with pontos and GitHub Actions"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-user-token }}
