name: "Python Codecov Action"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to upload coverage to codecov.io for Python package by using Poetry."

inputs:
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
  test-command:
    description: "Command to run the tests"
    required: true
    default: "-m unittest"
  token:
    description: "Upload token for codecov.io. Required for private repositories."
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache:
    description: "Cache dependencies by setting it to 'true'."
  cache-dependency-path:
    description: "Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies by setting it to 'true'."
  install-dependencies:
    description: "Install project dependencies. Default is 'true'. Set to an other string then 'true' to not install the dependencies."
    default: "true"
  working-directory:
    description: "Working directory where to run the action"
    default: ${{ github.workspace }}
  codecov-upload:
    description: "Upload coverage to codecov.io. Default is 'true'. Set to an other string then 'true' to disable the upload."
    default: "true"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: greenbone/actions/poetry@v3
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
        install-dependencies: ${{ inputs.install-dependencies }}
        working-directory: ${{ inputs.working-directory }}
    - run: poetry run coverage run ${{ inputs.test-command }}
      shell: bash
      name: Run unit tests with coverage
      working-directory: ${{ inputs.working-directory }}
    - run: poetry run coverage xml
      shell: bash
      name: Create coverage XML report
      working-directory: ${{ inputs.working-directory }}
    - uses: codecov/codecov-action@v3
      if: ${{ inputs.codecov-upload == 'true' }}
      with:
        token: ${{ inputs.token }}
        fail_ci_if_error: true
      name: Upload coverage to codecov.io
