name: "Python Codecov Action"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to upload coverage to codecov.io for Python package by using Poetry."

inputs:
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
  package-manager:
    description: "Package manager to use, either 'poetry' or 'uv'. Default is 'poetry'."
    default: "poetry"
  test-command:
    description: "Command to run the tests"
    required: true
    default: "-m unittest"
  token:
    description: "Upload token for codecov.io. Required for private repositories."
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  uv-version:
    description: "Use a specific uv version. By default the latest release is used."
  cache:
    description: "Cache dependencies by setting it to 'true'."
  cache-dependency-path:
    description: "Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies by setting it to 'true'."
  install-dependencies:
    description: "Install project dependencies. Default is 'true'. Set to an other string then 'true' to not install the dependencies."
    default: "true"
  working-directory:
    description: "Working directory where to run the action"
    default: ${{ github.workspace }}
  codecov-upload:
    description: "Upload coverage to codecov.io. Default is 'true'. Set to an other string then 'true' to disable the upload."
    default: "true"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      if: ${{ inputs.package-manager == 'poetry' }}
      uses: greenbone/actions/poetry@v3
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
        install-dependencies: ${{ inputs.install-dependencies }}
        working-directory: ${{ inputs.working-directory }}
    - name: Install uv
      if: ${{ inputs.package-manager == 'uv' }}
      uses: greenbone/actions/uv@v3
      with:
        python-version: ${{ inputs.python-version }}
        uv-version: ${{ inputs.uv-version }}
        enable-cache: ${{ inputs.cache }}
        cache-dependency-glob: ${{ inputs.cache-dependency-path }}
        working-directory: ${{ inputs.working-directory }}
    - name: Run unit tests with coverage
      run: ${{ inputs.package-manager }} run coverage run ${{ inputs.test-command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Create coverage XML report
      run: ${{ inputs.package-manager }} run coverage xml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Upload coverage to codecov.io
      if: ${{ inputs.codecov-upload == 'true' }}
      uses: codecov/codecov-action@v6
      with:
        token: ${{ inputs.token }}
        fail_ci_if_error: true
