name: "Send mattermost message"
description: "Send a mattermost message"

inputs:
  MATTERMOST_WEBHOOK_URL:
    description: "Mattermost webhook url"
    deprecationMessage: "Deprecated. Use url instead."
  MATTERMOST_CHANNEL:
    description: "Mattermost channel"
    deprecationMessage: "Deprecated. Use channel instead."
  MATTERMOST_HIGHLIGHT:
    description: "highlight users in channel. Deprecated."
    deprecationMessage: "Deprecated. Use highlight instead."
  commit-message:
    description: Git commit message to use
    deprecationMessage: "Deprecated. Connected commit message to commit will be used"
  url:
    description: "Mattermost webhook url"
  channel:
    description: "Mattermost channel"
  highlight:
    description: "highlight users in channel"
  branch:
    description: Git branch. Default is 'github.ref_name'.
    default: ${{ github.ref_name }}
  commit:
    description: Git commit. Default is 'github.sha'.
    default: ${{ github.sha }}
  message:
    description: "Enter a markdown formatted text message. Note: Setting a string in this argument ignores all other arguments."
  repository:
    description: GitHub repository (org/repo). Default is 'github.repository'
    default: ${{ github.repository }}
  status:
    description: Specifies the notification status. Options success or failure. Default is automatic detected by 'GITHUB_EVENT_PATH' json.
  skip-installation-on:
    description: Skip mn-notify installation on selected runner. Default is self-hosted-generic.
    default: "self-hosted-generic"
  workflow:
    description: GitHub workflow ID. Default is 'github.run_id'.
    default: ${{ github.run_id }}
  workflow-name:
    description: GitHub workflow name. Default is 'github.workflow'
    default: ${{ github.workflow }}
  shortline:
    description: "Set to 'true' to output git changes in a single line for a more concise format."
    default: "false"
  # NEW INPUTS
  product: 
    description: "Product name (asset, lookout, detect, management-console, security-intelligence, enterprise-containers)"
    required: false
  stage:
    description: "Deployment stage (dev, integration, testing, staging, production)"
    required: false
  version:
    description: "Product or service version (semver format, e.g., 1.15.1-alpha.10)"
    required: false
  service:
    description: "Service name for service-update notifications"
    required: false
  from-stage:
    description: "Source stage for stage-transition notifications (e.g., testing)"
    required: false
  to-stage:
    description: "Target stage for stage-transition notifications (e.g., staging)"
    required: false
  notification-type:
    description:  "Type of notification:  deployment, service-update, stage-transition, release, hotfix"
    required: false
    default: ""
  changed-services:
    description: "Comma-separated list of changed services"
    required: false

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Checkout
      # we need a checkout to determine the commit-message per git
      # if commit is set but commit-message is not
      if: inputs.commit && !inputs.commit-message
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: ${{ inputs.commit }}

    - name: Install
      if: ${{ !startsWith(runner.name, inputs.skip-installation-on) }}
      uses: greenbone/actions/pipx@v3
      id: pipx
      with:
        python-version: "3.10"
        install: mattermost-notify
        install-version: "26.1.1"

    - name: Set Channel and Webhook
      shell: bash
      run: |
        echo "POS_ARGS=${{ inputs.MATTERMOST_WEBHOOK_URL }}${{ inputs.url }} ${{ inputs.MATTERMOST_CHANNEL }}${{ inputs.channel }}" >> $GITHUB_ENV

    - name: Inputs for Github success notifications
      shell: bash
      run: |
        ARGS=()

        if [ -n "${{ inputs.commit }}" ]; then
          ARGS+=(--commit "${{ inputs.commit }}")
        fi

        if [ -n "${{ inputs.branch }}" ]; then
          ARGS+=(--branch "${{ inputs.branch }}")
        fi

        if [ -n "${{ inputs.repository }}" ]; then
          ARGS+=(--repository "${{ inputs.repository }}")
        fi

        if [ -n "${{ inputs.status }}" ]; then
          ARGS+=(--status "${{ inputs.status }}")
        fi

        if [ -n "${{ inputs.workflow }}" ]; then
          ARGS+=(--workflow "${{ inputs.workflow }}")
        fi

        if [ -n "${{ inputs.workflow-name }}" ]; then
          ARGS+=(--workflow_name \""${{ inputs.workflow-name }}\"")
        fi

        if [[ ! "${{ inputs.shortline }}" == "false" ]]; then
          ARGS+=(--short)
        fi

        if [ -n "${{ inputs.MATTERMOST_HIGHLIGHT }}" ] || [ -n "${{ inputs.highlight }}" ]; then
          ARGS+=(--highlight)
          # Add every highlight element as its own string
          IFS=' ' read -ra HIGHLIGHTS <<< "${{ inputs.MATTERMOST_HIGHLIGHT }} ${{ inputs.highlight }}"
          for HIGHLIGHT in "${HIGHLIGHTS[@]}"; do
            ARGS+=("$HIGHLIGHT")
          done
        fi
        #Add new arguments
        if [ -n "${{ inputs.product }}" ]; then
          ARGS+=(--product "${{ inputs.product }}")
        fi

        if [ -n "${{ inputs.stage }}" ]; then
          ARGS+=(--stage "${{ inputs.stage }}")
        fi

        if [ -n "${{ inputs.version }}" ]; then
          ARGS+=(--version "${{ inputs.version }}")
        fi

        if [ -n "${{ inputs.service }}" ]; then
          ARGS+=(--service "${{ inputs.service }}")
        fi

        if [ -n "${{ inputs.from-stage }}" ]; then
          ARGS+=(--from-stage "${{ inputs.from-stage }}")
        fi

        if [ -n "${{ inputs.to-stage }}" ]; then
          ARGS+=(--to-stage "${{ inputs.to-stage }}")
        fi

        if [ -n "${{ inputs.notification-type }}" ] && [ "${{ inputs.notification-type }}" != "" ]; then
          ARGS+=(--notification-type "${{ inputs.notification-type }}")
        fi

        if [ -n "${{ inputs.changed-services }}" ]; then
          ARGS+=(--changed-services "${{ inputs.changed-services }}")
        fi

        echo "ARGS=${ARGS[@]}" >> $GITHUB_ENV

    - name: Use markdown formatted message, if it is set.
      if: ${{ inputs.message }}
      shell: bash
      run: printf "ARGS=--free %q" '${{ inputs.message }}' >> $GITHUB_ENV
    - name: Execute Mattermost-Notify
      shell: bash
      run: mnotify-git ${{ env.POS_ARGS }} ${{ env.ARGS }}
