name: "Send mattermost message"
description: "Send a mattermost message"
inputs:
  MATTERMOST_WEBHOOK_URL:
    description: "Mattermost webhook url"
    required: true
  MATTERMOST_CHANNEL:
    description: "Mattermost channel"
    required: true
  MATTERMOST_HIGHLIGHT:
    description: "highlight users in channel"
    required: false
branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade mattermost-notify
      shell: bash
    - name: Create the Mattermost Message
      shell: bash
      run: |
        if [ "${{ inputs.MATTERMOST_HIGHLIGHT }}" ] ; then
          mnotify-git ${{ inputs.MATTERMOST_WEBHOOK_URL }} ${{ inputs.MATTERMOST_CHANNEL }} \
            --highlight ${{ inputs.MATTERMOST_HIGHLIGHT }}
        else
          mnotify-git ${{ inputs.MATTERMOST_WEBHOOK_URL }} ${{ inputs.MATTERMOST_CHANNEL }}
        fi
