name: "Send mattermost message"
description: "Send a mattermost message"
inputs:
  MATTERMOST_WEBHOOK_URL:
    description: "Mattermost webhook url"
    required: true
  MATTERMOST_CHANNEL:
    description: "Mattermost channel"
    required: true
  MATTERMOST_HIGHLIGHT:
    description: "highlight users in channel"
    required: false
branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: python
      with:
        python-version: "3.10"
    - name: Virtual Environment
      id: virtualenv
      run: |
        echo "path=${{ github.action_path }}/${{ github.action }}-venv" >> $GITHUB_OUTPUT
        echo "name=${{ github.action }}-venv" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache Virtual Environment
      id: cache-virtualenv
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ steps.virtualenv.outputs.name }}
        path: ${{ steps.virtualenv.outputs.path }}
    - name: Create virtual environment
      if: ${{ steps.cache-virtualenv.outputs.cache-hit != 'true' }}
      run: |
        python -m venv ${{ steps.virtualenv.outputs.path }}
      shell: bash
    - run: |
        source ${{ steps.virtualenv.outputs.path }}/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade mattermost-notify
      shell: bash
    - name: Create the Mattermost Message
      shell: bash
      run: |
        source ${{ steps.virtualenv.outputs.path }}/bin/activate
        if [ "${{ inputs.MATTERMOST_HIGHLIGHT }}" ] ; then
          mnotify-git ${{ inputs.MATTERMOST_WEBHOOK_URL }} ${{ inputs.MATTERMOST_CHANNEL }} \
            --highlight ${{ inputs.MATTERMOST_HIGHLIGHT }}
        else
          mnotify-git ${{ inputs.MATTERMOST_WEBHOOK_URL }} ${{ inputs.MATTERMOST_CHANNEL }}
        fi
