name: "Build XML documentation and upload coverage"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to upload documentation coverage to codecov.io for C Lang repository. Requires to run with the greenbone/doxygen docker image."

inputs:
  token:
    description: "Upload token for codecov.io."

branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install coverxygen and codecov
      shell: bash
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip install setuptools --upgrade
        pip install 'coverxygen>=1.3.1' codecov
    - name: Generate documentation (XML)
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DSKIP_SRC=1 ..
        make doc-xml
    - name: Establish documentation coverage
      shell: bash
      run: |
        . .venv/bin/activate
        python -m coverxygen --src-dir ${{ github.workspace }} \
        --xml-dir build/doc/generated/xml/ --output lcov.info
    - name: Upload documentation coverage to codecov
      uses: codecov/codecov-action@v4
      with:
        files: lcov.info
        token: ${{ inputs.token }}
        flags: documentation
