name: "Detect hidden unicode"
description: "Detects hidden unicode in newly committed config files."

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    # According to this comment on SO: https://stackoverflow.com/questions/74265821/get-modified-files-in-github-actions
    - uses: actions/checkout@v5
      with:
        fetch-depth: 2

    # ‍https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-a-multiline-string
    # https://medium.com/@ibraheemabukaff/github-actions-exporting-multi-line-one-line-value-environment-variable-5bb86d01e866
    - name: Store a list of the changed files in this PR
      shell: bash
      run: |
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        echo "$(git diff --name-only HEAD^1 HEAD)" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - uses: actions/checkout@v5
      with:
        repository: juriku/hidden-characters-detector
        path: hidden-characters-detector

    - name: Install hidden-characters-detector
      shell: bash
      run: |
        cd hidden-characters-detector
        pip install -r requirements.txt
        chmod +x hidden-characters-detector.py
        cd ..

    - name: Run hidden unicode detector against the list of changed files
      shell: bash
      run: |
        echo "Scan the following files for hidden unicode:"
        echo "${{ env.CHANGED_FILES }}"
        while IFS= read -r line ;
        echo "SCAN START"
        echo "CURRENT FILE: $line"
        do ./hidden-characters-detector/hidden-characters-detector.py -f $line --check-ivs --fail
        echo "SCAN END"
        done <<< "${{ env.CHANGED_FILES }}"
