name: "Detect hidden unicode"
description: "Detects hidden unicode in newly committed config files."

inputs:
  python-version:
    description: "Python version to use for running the action"
    default: "3.10"
  github-token:
    description: "GH Token for writing/editing a comment to/in a PR"
    required: true
  pr-comment:
    description: "Write a summary of the scan as comment to the PR"
    default: true
  detect-hidden-unicode-args:
    description: "Args passed to detect-hidden-unicode script"
    default: ""
  filter:
    description: "The regex filter being applied to the file selection"
    default: ""
  log-level:
    description: "The log level of the detect-hidden-unicode action"
    options:
      - NONE
      - WARNING
      - DEBUG
    default: WARNING

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install detect-hidden-unicode
      uses: greenbone/actions/uv@v3
      with:
        install: "${{ github.action_path }}/."
        python-version: ${{ inputs.python-version }}
        working-directory: ${{ github.action_path }}

    # According to this comment on SO: https://stackoverflow.com/questions/74265821/get-modified-files-in-github-actions
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        fetch-depth: 2

    - name: Run hidden unicode detector against the list of changed files
      shell: bash
      run: |
        detect-hidden-unicode "$GITHUB_WORKSPACE/" --filter '${{ inputs.filter }}' --log_level '${{ inputs.log-level }}' | tee -a "$GITHUB_WORKSPACE/output"

    - name: Publish PR Comment
      if: ${{ inputs.pr-comment == true || inputs.pr-comment == 'true' }}
      shell: bash
      run: |
        # Write a comment to the PR, which contains the Scan Output
        if [ -s PR_COMMENT.md ]; then
          gh pr comment ${{ github.event.pull_request.number }} --body-file PR_COMMENT.md --create-if-none --edit-last
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Fail if markers are detected
      shell: bash
      run: |
        if [ -s output ]; then
          grep -vqz "hidden markers detected" output
        fi
