name: "Detect hidden unicode"
description: "Detects hidden unicode in newly committed config files."

inputs:
  python-version:
    description: "Python version to use for running the action"
    default: "3.10"
  github-token:
    description: "GH Token for writing/editing a comment to/in a PR"
    required: true
  pr-comment:
    description: "Write a summary of the scan as comment to the PR"
    default: true
  detect-hidden-unicode-args:
    description: "Args passed to detect-hidden-unicode script"
    default: ""


branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Install detect-hidden-unicode
      uses: greenbone/actions/uv@v3
      with:
        install: "${{ github.action_path }}/."
        python-version: ${{ inputs.python-version }}
        working-directory: ${{ github.action_path }}
  
    # According to this comment on SO: https://stackoverflow.com/questions/74265821/get-modified-files-in-github-actions
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      with:
        fetch-depth: 2

    - name: Run hidden unicode detector against the list of changed files
      shell: bash
      run: |
        detect-hidden-unicode "$GITHUB_WORKSPACE/" ${{ inputs.detect-hidden-unicode-args }} | tee -a "$GITHUB_WORKSPACE/PR_COMMENT.md"

    - name: Publish PR Comment
      if: ${{ inputs.pr-comment == true || inputs.pr-comment == 'true' }}
      shell: bash
      run: |
        # Write a comment to the PR, which contains the Scan Output
        if [ -s PR_COMMENT.md ]; then
          gh pr comment ${{ github.event.pull_request.number }} --body-file PR_COMMENT.md --create-if-none --edit-last
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Fail if markers are detected
      shell: bash
      run: |
        if [ -s PR_COMMENT.md ]; then
          grep -vqz "hidden markers detected" PR_COMMENT.md
        fi
