name: "Greenbone Conventional Commits Action"
description: "A GitHub Action to check for conventional commits"
author: "Björn Ricks"
inputs:
  token:
    description: "GitHub Token for authentication"
    default: ${{ github.token }}
  python-version:
    description: "Python version to use for running the action"
    required: false
    default: "3.10"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies. Default is 'true'. Set to an other string then 'true' to disable the cache."
    default: "true"
  ref:
    description: "The branch, tag or SHA to checkout."
  base-ref:
    description: "Use a specific base ref. Defaults to 'github.base_ref'."
    default: ${{ github.base_ref }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@v2
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        working-directory: ${{ github.action_path }}
        without-dev: "true"
        cache-dependency-path: ${{ github.action_path }}/poetry.lock
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
    - name: Run conventional commits
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        poetry run conventional-commits \
          --token ${{ inputs.token }} \
          --base-ref ${{ inputs.base-ref }} \
          --event-path ${{ github.event_path }} \
          --repository ${{ github.repository }} \
          --working-directory ${{ github.workspace }}
