name: "Greenbone Conventional Commits Action"
description: "A GitHub Action to check for conventional commits. It looks for commits between base and head ref."
author: "Björn Ricks"
inputs:
  token:
    description: "GitHub Token for authentication"
    default: ${{ github.token }}
  python-version:
    description: "Python version to use for running the action"
    required: false
    default: "3.10"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies. Default is 'true'. Set to an other string then 'true' to disable the cache."
    default: "true"
  head-ref:
    description: "Use as specific head ref. Defaults to 'github.event.pull_request.head.sha'"
    default: ${{ github.event.pull_request.head.sha }}
  base-ref:
    description: "Use a specific base ref. Defaults to 'github.event.pull_request.base.sha'."
    default: ${{ github.event.pull_request.base.sha }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # fetch-depth create a shallow clone https://www.git-scm.com/docs/shallow
        # with inputs.base-ref as root ref of the repo
        fetch-depth: 1
        ref: ${{ inputs.base-ref }}
    - name: Fetch commits
      # fetch commits from head ref. It stops at base ref because we have a
      # shallow repo.
      run: |
        git fetch ${{ inputs.head-ref }}
      shell: bash
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@v2
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        working-directory: ${{ github.action_path }}
        without-dev: "true"
        cache-dependency-path: ${{ github.action_path }}/poetry.lock
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
    - name: Run conventional commits
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        poetry run conventional-commits \
          --token ${{ inputs.token }} \
          --base-ref ${{ inputs.base-ref }} \
          --head-ref ${{ inputs.head-ref }} \
          --event-path ${{ github.event_path }} \
          --repository ${{ github.repository }} \
          --working-directory ${{ github.workspace }}
