---
- name: Run dev environment deployment
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  ignore_errors: false
  tasks:
    - name: Load vars
      ansible.builtin.include_vars: "{{ base_dir }}/{{ vars_path }}"

    - name: Deployment environment
      block:
        - name: Create tmp folder
          ansible.windows.win_tempfile:
            state: directory
            suffix: deployment
          register: tmp

        - name: Copy folder
          ansible.windows.win_copy:
            src: "{{ base_dir }}/{{ item }}"
            dest: "{{ tmp.path }}/"
          loop: >-
            {%- if copy | type_debug == 'list' -%}
              {{ copy }}
            {%- else -%}
              {{ copy | split }}
            {%- endif -%}
          when: copy is defined

        - name: Run deployment
          ansible.windows.win_powershell:
            chdir: "{{ tmp.path }}"
            parameters: "{{ env | default({}) }}"
            script: "{{ cmd }}"
          register: deployment_result
          when: cmd is defined
      always:
        - name: Deployment outout
          ansible.builtin.debug:
            msg: "{{ deployment_result.output }}"
          when: deployment_result.output is defined

        - name: Deployment error output
          ansible.builtin.debug:
            msg: "{{ deployment_result.error }}"
          when: deployment_result.error is defined

        - name: Remove tmp folder
          ansible.windows.win_file:
            path: "{{ tmp.path }}"
            state: absent
