name: "Upload to PyPI"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "Action to build and upload a release via uv to PyPI"

inputs:
  python-version:
    description: "Python version to use for this action"
    default: "3.10"
  pypi-token:
    description: "Token for uploading the build to PyPI"
    required: false
  ref:
    description: The branch, tag or SHA to checkout. Default depends on the event (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: greenbone/actions/uv@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Build
      run: |
        uv build
      shell: bash
    - name: Upload
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        password: ${{ inputs.pypi-token }}
