name: "Upload to PyPI"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "Action to build and upload a release via uv to PyPI"

inputs:
  python-version:
    description: "Python version to use for this action"
    default: "3.10"
  pypi-token:
    description: "Token for uploading the build to PyPI"
    required: false
  ref:
    description: The branch, tag or SHA to checkout. Default depends on the event (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pip and uv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv
      shell: bash
    - name: Install dependencies and sync environment
      run: |
        uv sync
      shell: bash
    - name: Build
      run: |
        uv build
      shell: bash
    - name: Verify package metadata
      run: |
        python -m pip install --upgrade twine
        python -m twine check dist/*
      shell: bash
    - name: Upload
      run: |
        if [ -n "${{ inputs.pypi-token }}" ]; then
          python -m twine upload dist/* --username __token__ --password "${{ inputs.pypi-token }}"
        else
          echo "No PyPI token provided, skipping upload"
        fi
      shell: bash
