name: "Greenbone Download Artifact Action"
description: "GitHub Action to download artifacts of a workflow run"
author: "Björn Ricks"
inputs:
  token:
    description: "GitHub Token for authentication"
    default: ${{ github.token }}
  repository:
    description: "Repository to download the artifacts from. Defaults to the current repository."
    required: false
  workflow:
    description: "Workflow to download the artifacts from. Either a workflow ID or file path. For example `ci.yml`."
    required: true
  workflow-events:
    description: "Consider only workflow runs triggered by the specified events. Default: schedule, workflow_dispatch"
    default: "schedule, workflow_dispatch"
    required: false
  branch:
    description: "The git branch for the workflow to download the artifacts from."
    required: false
    default: "main"
  name:
    description: "Artifact name to be downloaded. If not set, all artifacts will be downloaded."
    required: false
  allow-not-found:
    description: "Set to 'true' to not fail if workflow or artifact could not be found."
    default: "false"
  path:
    description: "Path where to store the downloaded artifacts."
    required: false
    default: "."
  user:
    description: "User ID for ownership of the downloaded artifacts."
    required: false
  group:
    description: "Group ID for ownership of the downloaded artifacts."
    required: false
  python-version:
    description: "Python version to use for running the action"
    required: false
    default: "3.10"
  poetry-version:
    description: "Use a specific poetry version. By default the latest release is used."
  cache-poetry-installation:
    description: "Cache poetry and its dependencies. Default is 'true'. Set to an other string then 'true' to disable the cache."
    default: "true"
outputs:
  downloaded-artifacts:
    description: List of downloaded artifact names as JSON array string
    value: ${{ steps.download.outputs.downloaded-artifacts }}
  total-downloaded-artifacts:
    description: Number of downloaded artifacts
    value: ${{ steps.download.outputs.total-downloaded-artifacts }}

runs:
  using: "composite"
  steps:
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@v3
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        working-directory: ${{ github.action_path }}
        without-dev: "true"
        cache-dependency-path: ${{ github.action_path }}/poetry.lock
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
    - name: Run download artifact
      shell: bash
      id: download
      working-directory: ${{ github.action_path }}
      run: |
        poetry run download-artifact \
          --token ${{ inputs.token }} \
          --repository ${{ inputs.repository }} \
          --workflow ${{ inputs.workflow }} \
          --workflow-events "${{ inputs.workflow-events }}" \
          --branch ${{ inputs.branch }} \
          --name ${{ inputs.name }} \
          --allow-not-found ${{ inputs.allow-not-found }} \
          --path ${{ inputs.path }} \
          --user ${{ inputs.user }} \
          --group ${{ inputs.group }}
