[project]
name = "download-artifact-action"
version = "1.0.0"
description = "A GitHub Action to download artifacts of a workflow run"
authors = [{ name = "Björn Ricks", email = "bjoern.ricks@greenbone.net" }]
requires-python = ">=3.10,<4"
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["pontos>=23.3.0"]

[project.scripts]
download-artifact = "action.artifact:main"

[dependency-groups]
dev = ["autohooks-plugin-ruff>=25.3.1"]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["action"]
module-root = ""
namespace = true

[tool.ruff]
line-length = 80
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I", "PLE", "PLW"]

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[tool.autohooks]
mode = "uv"
pre-commit = ['autohooks.plugins.ruff.check', 'autohooks.plugins.ruff.format']
