[project]
name = "download-artifact-action"
version = "1.0.0"
description = "A GitHub Action to download artifacts of a workflow run"
authors = [{ name = "Björn Ricks", email = "bjoern.ricks@greenbone.net" }]
requires-python = ">=3.10,<4"
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["pontos>=23.3.0"]

[project.scripts]
download-artifact = "action.artifact:main"

[dependency-groups]
dev = [
    "autohooks-plugin-pylint>=22.8.0",
    "autohooks-plugin-isort>=22.8.0",
    "autohooks-plugin-black>=22.8.0",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["action"]
module-root = ""
namespace = true

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[tool.black]
line-length = 80
target-version = ["py310", "py311", "py312", "py313", "py314"]
exclude = '''
/(
    \.git
  | \.venv
  | \.github
  | \.vscode
  | _build
  | build
  | dist
  | docs
)/
'''

[tool.isort]
profile = "black"
line_length = 80

[tool.autohooks]
mode = "poetry"
pre-commit = [
    'autohooks.plugins.black',
    'autohooks.plugins.isort',
    'autohooks.plugins.pylint',
]
