name: Helm build and push chart
description: Push helm chart to OCI-based registries
inputs:
  charts-path:
    description: Path to charts base folder
    default: ./charts
  chart-name:
    description: "Chart to build and push"
    required: true
  registry:
    description: Registry
    default: "ghcr.io"
  registry-subpath:
    description: Registry subpath to place the helm chart in
  registry-user:
    description: Registry login user
    required: true
  registry-token:
    description: Registry login password/token
    required: true
  gpg-secret-key:
    description: Base64 encoded gpg secret key for chart sign
    required: false
  gpg-secret-name:
    description: Gpg secret key name from gpg secret key
    required: false

outputs:
  tag:
    description: Helm chart url's with tag.
    value: ${{ steps.push.outputs.tag }}
  digest:
    description: The helm chart digest.
    value: ${{ steps.push.outputs.digest }}

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Helm registry login 
      shell: bash
      run: |
        helm registry login \
          -u '${{ inputs.registry-user }}' \
          -p '${{ inputs.registry-token }}' \
          '${{ inputs.registry }}'
    - name: Set gpg secret key
      if: ${{ inputs.gpg-secret-name }}
      shell: bash
      run: |
        echo "${{ inputs.gpg-secret-key }}" | base64 -d > /tmp/secret-key.gpg
        chmod 0600 /tmp/secret-key.gpg
    - name: Build and signing
      shell: bash
      run: |
        chart="${{ inputs.charts-path }}/${{ inputs.chart-name }}"
        # Load helm chart dependency's
        helm dependency update "$chart"
        # Build helm chart
        if [ "${{ inputs.gpg-secret-name }}" ]; then
          helm package \
            --sign \
            --key "${{ inputs.gpg-secret-name }}" \
            --keyring /tmp/secret-key.gpg \
            "$chart"
        else
          helm package "$chart"
        fi
    - name: Push
      id: push
      shell: bash
      run: |
        cmd="push ${{ inputs.chart-name }}-*.tgz oci://${{ inputs.registry }}/${{ github.repository_owner }}/"
        # Add subpath if exist
        if [ "${{ inputs.registry-subpath }}" ]; then
          echo "Add subpath ${{ inputs.registry-subpath }}"
          cmd+="${{ inputs.registry-subpath }}/"
        fi
        # Run helm push
        output="$(helm $cmd)"
        echo "$output"
        # Get helm path and helm digest
        pushed="$(echo "$output" | awk '/Pushed:/{print $2}')"
        digest="$(echo "$output" | awk '/Digest:/{print $2}')"
        # Set outputs
        echo "tag=$pushed" >> "$GITHUB_OUTPUT"
        echo "digest=$digest" >> "$GITHUB_OUTPUT"
    - name: Cleanup
      shell: bash
      run: |
        rm -f "${{ inputs.chart-name }}-*.tgz"
        rm -f "${{ inputs.chart-name }}-*.tgz.prov"
        rm -f /tmp/secret-key.gpg
