name: Helm build and push chart
description: Push helm chart to OCI-based registries
inputs:
  charts-path:
    description: Path to charts base folder
    default: ./charts
  chart-name:
    description: "Chart to build and push"
    required: true
  registry:
    description: Registry
    default: ${{ vars.IMAGE_REGISTRY }}
  registry-subpath:
    description: Registry subpath to place the helm chart in
    required: true
  registry-user:
    description: Registry login user
    required: true
  registry-token:
    description: Registry login password/token
    required: true
branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Helm registry login 
      shell: bash
      run: |
        helm registry login \
          -u '${{ inputs.registry-user }}' \
          -p '${{ inputs.registry-token }}' \
          '${{ inputs.registry }}'
    - name: Helm build and upload package
      shell: bash
      run: |
        helm dependency update '${{ inputs.charts-path }}/${{ inputs.chart-name }}'
        helm package '${{ inputs.charts-path }}/${{ inputs.chart-name }}'
    - name: Push with subpath
      if: ${{ inputs.registry-subpath }}
      run: helm push ${{ inputs.chart-name }}-*.tgz 'oci://${{ inputs.registry }}/${{ inputs.registry-subpath }}'
    - name: Push without subpath
      if: ${{ !inputs.registry-subpath }}
      run: helm push ${{ inputs.chart-name }}-*.tgz 'oci://${{ inputs.registry }}'
    - name: Cleanup
        rm -f "${{ inputs.chart-name }}-*.tgz"
