name: Helm build and push chart
description: Push helm chart to OCI-based registries
inputs:
  charts-path:
    description: Path to charts base folder
    default: ./charts
    required: false
  chart-name:
    description: "Chart to build and push"
    required: true
  registry:
    description: Registry
    required: true
  registry-url:
    description: Registry url
    required: true
  registry-user:
    description: Registry login user
    required: true
  registry-token:
    description: Registry login password/token
    required: true
branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Helm registry login 
      shell: bash
      run: |
        helm registry login \
          -u '${{ inputs.registry-user }}' \
          -p '${{ inputs.registry-token }}' \
          '${{ inputs.registry }}'
    - name: Helm build and upload package
      shell: bash
      run: |
        helm dependency update '${{ inputs.charts-path }}/${{ inputs.chart-name }}'
        helm package '${{ inputs.charts-path }}/${{ inputs.chart-name }}'
        helm push ${{ inputs.chart-name }}-*.tgz '${{ inputs.registry-url }}'
        rm -f "${{ inputs.chart-name }}-*.tgz"
