name: "Check Version"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to check version information via pontos"
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v4
      id: python
      with:
        python-version: "3.10"
    - name: Virtual Environment
      id: virtualenv
      run: |
        echo "path=${{ github.action_path }}/${{ github.action }}-venv" >> $GITHUB_OUTPUT
        echo "name=${{ github.action }}-venv" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache Virtual Environment
      id: cache-virtualenv
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ steps.virtualenv.outputs.name }}
        path: ${{ steps.virtualenv.outputs.path }}
    - name: Create virtual environment
      if: ${{ steps.cache-virtualenv.outputs.cache-hit != 'true' }}
      run: |
        python -m venv ${{ steps.virtualenv.outputs.path }}
      shell: bash
    - name: Install pontos
      run: |
        source ${{ steps.virtualenv.outputs.path }}/bin/activate
        python -m pip install -U pip
        python -m pip install pontos
      shell: bash
    - name: Check version information
      run: |
        source ${{ steps.virtualenv.outputs.path }}/bin/activate
        python -m pontos.version verify current
      shell: bash
      working-directory: ${{ github.workspace }}
