name: "Check Version"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to check version information via pontos"

inputs:
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
  working-directory:
    description: "A working directory where to check the versioning"
    default: ${{ github.workspace }}

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }} and pontos
      uses: greenbone/actions/setup-pontos@v3
      id: virtualenv
      with:
        python-version: ${{ inputs.python-version}}
    - name: Check version information
      run: |
        source ${{ steps.virtualenv.outputs.activate }}
        python -m pontos.version verify current
      shell: bash
      working-directory: ${{ inputs.working-directory }}
