name: "pipx"
description: "A GitHub Action for using pipx"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"

inputs:
  python-version:
    description: Setup a specific Python version
  python-path:
    description: |
      Path to the Python binary to use. Passing python-path allows for setting
      up a Python version before using this action and running pipx with the set
      up Python version.
  cache:
    description: "Enable caching for the installed application. Disabled by default. 'true' to enable."
    default: "false"
  install:
    description: Python application to install
  install-version:
    description: Use a specific version of the application to install. For example '1.2.3'.

outputs:
  home:
    description: Path to the pipx python application
    value: ${{ steps.settings.outputs.home }}
  bin:
    description: Path to the bin directory where all applications can be run from
    value: ${{ steps.settings.outputs.bin }}
  venvs:
    description: Path to the directory where the virtual environments are stored
    value: ${{ steps.settings.outputs.venvs }}
  shared:
    description: Path where shared python packages like pip or wheel are installed
    value: ${{ steps.settings.outputs.shared }}
  cache-hit:
    description: "'true' if the cache has been hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      if: inputs.python-version
      uses: actions/setup-python@v4
      id: python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Pipx version
      id: version
      run: |
        PIPX_VERSION=$(pipx --version)

        IFS='.' read -r major minor patch << EOF
        $PIPX_VERSION
        EOF

        echo "version=$PIPX_VERSION" >> $GITHUB_OUTPUT
        echo "major=$major" >> $GITHUB_OUTPUT
        echo "minor=$minor" >> $GITHUB_OUTPUT
        echo "patch=$patch" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get pipx settings
      continue-on-error: true
      id: settings
      run: |
        if [[ "${{ steps.version.outputs.major }}" -lt 1 || ( "${{ steps.version.outputs.major }}" -eq 1 && "${{ steps.version.outputs.minor }}" -lt 1 ) ]]; then
          echo "::warning::pipx version ${{ steps.version.outputs.version}} is installed. At least version 1.1.0 is required to provide outputs in this action! Try to install newer version with pip."
          python3 -m pip install "pipx>=1.1.0"
        fi

        pipx environment
        echo "home=$(pipx environment -v PIPX_HOME)" >> $GITHUB_OUTPUT
        echo "bin=$(pipx environment -v PIPX_BIN_DIR)" >> $GITHUB_OUTPUT
        echo "venvs=$(pipx environment -v PIPX_LOCAL_VENVS)" >> $GITHUB_OUTPUT
        echo "shared=$(pipx environment -v PIPX_SHARED_LIBS)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Ensure pipx bin directory is in PATH
      run: |
        if [[ "$PATH" != *"${{ steps.settings.outputs.bin }}"* ]]; then
          echo "${{ steps.settings.outputs.bin }}" >> $GITHUB_PATH
        fi
      shell: bash
    - name: Show current PATH
      run: |
        echo $PATH
      shell: bash
    - name: Cache pipx venv for the application
      # cache venv only if an application will be installed and the user requested caching and no python path is set
      if: inputs.install && inputs.cache == 'true' && !inputs.python-path
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.settings.outputs.venvs }}/${{ inputs.install }}
        key: python-${{ steps.python.outputs.python-version }}-pipx-venv-${{ inputs.install }}-${{ inputs.install-version || 'latest' }}
    - name: Install application
      # install an application if an application should be installed and the user did not request caching, a python path is set or the cache was not hit
      if: inputs.install && (inputs.python-path || inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true')
      run: |
        if [ -n "${{ inputs.python-path }}" ]; then
          PYTHON_BIN="${{ inputs.python-path }}"
        else
          PYTHON_BIN="${{ steps.python.outputs.python-path }}"
        fi

        ARGS=""
        if [ -n "$PYTHON_BIN" ]; then
          ARGS="$ARGS --python $PYTHON_BIN"
        fi

        ARGS="$ARGS ${{ inputs.install }}"

        if [ -n "${{ inputs.install-version }}" ]; then
          ARGS="$ARGS==${{ inputs.install-version }}"
        fi

        echo $ARGS

        pipx install $ARGS
      shell: bash
    - name: Upgrade application
      # install an application if the latest version of the application should be installed and the user requested caching and the cache was hit and no python path was set
      if: inputs.install && !inputs.install-version && inputs.cache == 'true' && steps.cache.outputs.cache-hit == 'true' && !inputs.python-path
      run: |
        pipx upgrade ${{ inputs.install }}
      shell: bash
    - name: List installed applications
      run: |
        pipx list
      shell: bash
