name: "GoLang Linting"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to check linting and formatting Greenbone GoLang Projects"
inputs:
  version:
    description: "Golang version that should be installed"
    default: "1.18"
  generate:
    description: "Specify a command, used to generate additional code or documentation, that should get linted"
    default: "go generate"
  golangci-lint-version:
    description: "Specify the golangci-lint version (vX.YY, e.g. v1.50)"
    default: "v1.50"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: ${{ inputs.version }}
    - name: Generate code
      shell: bash
      run: ${{ inputs.generate }}
    - name: Use the linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ inputs.golangci-lint-version }}
