name: "GoLang Linting"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to check linting and formatting Greenbone GoLang Projects"
inputs:
  version:
    description: "Golang version that should be installed"
    default: "1.18"
  generate:
    description: "Specify a command, used to generate additional code or documentation, that should get linted"
    default: "go generate"
  golangci-lint-version:
    description: "Specify the golangci-lint version (vX.YY, e.g. v1.50)"
    default: "v1.50"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ inputs.version }}
    - name: Generate code
      shell: bash
      run: ${{ inputs.generate }}
    - name: Use the linter
      uses: golangci/golangci-lint-action@v8
      with:
        version: ${{ inputs.golangci-lint-version }}
