name: "GoLang Linting"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to check linting and formatting Greenbone GoLang Projects"
inputs:
  version:
    description: "Golang version that should be installed"
    default: "1.18"
  generate:
    description: "Specify a command, used to generate additional code or documentation, that should get linted"
    default: "go generate"
  golangci-lint-version:
    description: "Specify the golangci-lint version (vX.YY, e.g. v1.50)"
    default: "v1.50"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ inputs.version }}
    - name: Generate code
      shell: bash
      run: ${{ inputs.generate }}
    - name: Use the linter
      uses: golangci/golangci-lint-action@v9
      with:
        version: ${{ inputs.golangci-lint-version }}
