name: "Pontos Release Patch version"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action that creates a release [x.y.z -> x.y.z+1] for a project."

inputs:
  conventional-commits:
    description: "Use conventional commits, or Changelog file."
    default: "true"
  github-user:
    description: "Github user name."
    required: true
  github-user-mail:
    description: "Mail address for the given github user."
    required: true
  github-user-token:
    description: "Token with write rights required to create the release."
    required: true
  gpg-key:
    description: "GPG key, represented as a string. Required for signing assets of the release."
    required: false
  gpg-fingerprint:
    description: "GPG fingerprint, represented as a string. Required for signing assets of the release."
    required: false
  gpg-passphrase:
    description: "GPG passphrase, represented as a string. Required for signing assets of the release."
    required: false
  strategy:
    description: "What release strategy? ['calendar', 'major', 'minor', 'patch'], default: patch"
    default: "patch"
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
  ref:
    description: "Branch that should be released"
    default: ""

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 #for conventional commits
        persist-credentials: false
        ref: ${{ inputs.ref }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pontos
      run: |
        apt-get update && apt-get --assume-yes install python3-venv
        python3 -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade pontos
      shell: bash
    - name: Set git name, mail and origin
      run: |
        git config --global user.name "${{ inputs.github-user }}"
        git config --global user.email "${{ inputs.github-user-mail }}"
        git remote set-url origin https://${{ inputs.github-user-token }}@github.com/${{ github.repository }}
      shell: bash
    - name: Parse inputs
      run: |
        case ${{inputs.strategy}} in
          calendar | major | minor | patch )
            PREPARE_FLAGS="--release-type ${{ inputs.strategy }}"
            ;;
          *)
            PREPARE_FLAGS="--release-type patch"
            ;;
        esac
        echo "PREPARE_FLAGS=${PREPARE_FLAGS}" >> $GITHUB_ENV
      shell: bash
    - name: allow admin users bypassing protection on ${{ inputs.ref}} branch
      uses: greenbone/actions/admin-bypass@v2
      with:
        allow: "true"
        github-token: ${{ inputs.github-user-token }}
        branch: ${{ inputs.ref}}
    - name: Prepare release
      run: |
        . .venv/bin/activate
        pontos-release prepare ${{ env.PREPARE_FLAGS }}
      shell: bash
      env:
        GITHUB_USER: ${{ inputs.github-user }}
        GITHUB_TOKEN: ${{ inputs.github-user-token }}
    - name: Get release version
      shell: bash
      run: |
        . .venv/bin/activate
        VERSION=$(pontos-version show)
        echo "Releasing $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Create release
      run: |
        . .venv/bin/activate
        pontos-release release
      shell: bash
      env:
        GITHUB_USER: ${{ inputs.github-user }}
        GITHUB_TOKEN: ${{ inputs.github-user-token }}
    - name: disable bypassing protection on ${{ inputs.ref}} branch for admin users
      uses: greenbone/actions/admin-bypass@v2
      with:
        allow: "false"
        github-token: ${{ inputs.github-user-token }}
        branch: ${{ inputs.ref}}
    - name: Import gpg key from secrets
      run: |
        echo -e "${{ inputs.gpg-key }}" >> tmp.file
        gpg --pinentry-mode loopback --passphrase ${{ inputs.gpg-passphrase }} --import tmp.file
        rm tmp.file
      shell: bash
      if: ${{ inputs.gpg-key }} && ${{ inputs.gpg-fingerprint }} && ${{ inputs.gpg-passphrase }}
    - name: Sign assets for released version
      run: |
        echo "Signing assets for ${{env.VERSION}}"
        . .venv/bin/activate
        pontos-release sign --signing-key ${{ inputs.gpg-fingerprint }} --passphrase ${{ inputs.gpg-passphrase }} --release-version ${{ env.VERSION }}
      shell: bash
      if: ${{ inputs.gpg-key }} && ${{ inputs.gpg-fingerprint }} && ${{ inputs.gpg-passphrase }}
      env:
        GITHUB_USER: ${{ inputs.github-user }}
        GITHUB_TOKEN: ${{ inputs.github-user-token }}
