name: "Pontos Release Patch version"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: |
  "An action that is able to create a release for a project"
  "Supporting different programming languages and release types."

inputs:
  conventional-commits:
    description: "Deprecated."
  github-user:
    description: "Github user name on behalf of whom the actions will be executed."
    required: true
  github-user-mail:
    description: "Mail address for the given github user."
    required: true
  github-user-token:
    description: "Token with write rights required to create the release."
    required: true
  gpg-key:
    description: "GPG key, represented as a string. Required for signing assets of the release."
    required: false
  gpg-fingerprint:
    description: "GPG fingerprint, represented as a string. Required for signing assets of the release."
    required: false
  gpg-passphrase:
    description: "GPG passphrase, represented as a string. Required for signing assets of the release."
    required: false
  strategy:
    description: "Deprecated by release-type."
  release-type:
    description: |
      "What type of release should be executed?"
      "Supported: ['alpha', 'beta', 'calendar', 'major', 'minor', 'patch',  'release-candidate']; Default: patch"
    default: "patch"
  python-version:
    description: "Python version that should be installed"
    default: "3.10"
  ref:
    description: "This branches HEAD will be candidate of the next release"
    default: ""

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 #for conventional commits
        persist-credentials: false
        ref: ${{ inputs.ref }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pontos
      run: |
        python3 -m venv ${{ github.action_path }}/pontos-release-venv
        source ${{ github.action_path }}/pontos-release-venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade pontos
      shell: bash
    - name: Set git name, mail and origin
      run: |
        git config --global user.name "${{ inputs.github-user }}"
        git config --global user.email "${{ inputs.github-user-mail }}"
        git remote set-url origin https://${{ inputs.github-user-token }}@github.com/${{ github.repository }}
      shell: bash
    - name: Parse inputs
      run: |
        case ${{ inputs.release-type }} in
          alpha | beta | calendar | major | minor | patch | release-candidate)
            ARGS="--release-type ${{ inputs.release-type }}"
            ;;
          *)
            ARGS="--release-type patch"
            ;;
        esac
        if [[ "${{ inputs.strategy }}" ]]; then
          echo "strategy is deprecated, please use release-type argument"
          ARGS="--release-type ${{ inputs.strategy }}"
        fi
        echo "ARGS=${ARGS}" >> $GITHUB_ENV
      shell: bash
    - name: Allow admin users bypassing protection on ${{ inputs.ref}} branch
      uses: greenbone/actions/admin-bypass@v2
      with:
        allow: "true"
        github-token: ${{ inputs.github-user-token }}
        branch: ${{ inputs.ref}}
    - name: Create automatic release
      run: |
        source ${{ github.action_path }}/pontos-release-venv/bin/activate
        pontos-release release ${{ env.ARGS }}
      shell: bash
      env:
        GITHUB_USER: ${{ inputs.github-user }}
        GITHUB_TOKEN: ${{ inputs.github-user-token }}
    - name: Disable bypassing protection on ${{ inputs.ref}} branch for admin users
      if: always()
      uses: greenbone/actions/admin-bypass@v2
      with:
        allow: "false"
        github-token: ${{ inputs.github-user-token }}
        branch: ${{ inputs.ref}}
    - name: Import gpg key from secrets
      run: |
        echo -e "${{ inputs.gpg-key }}" >> tmp.file
        gpg --pinentry-mode loopback --passphrase ${{ inputs.gpg-passphrase }} --import tmp.file
        rm tmp.file
      shell: bash
      if: ${{ inputs.gpg-key }} && ${{ inputs.gpg-fingerprint }} && ${{ inputs.gpg-passphrase }}
    - name: Sign assets for released version
      run: |
        echo "Signing assets for ${{env.VERSION}}"
        source ${{ github.action_path }}/pontos-release-venv/bin/activate
        pontos-release sign --signing-key ${{ inputs.gpg-fingerprint }} --passphrase ${{ inputs.gpg-passphrase }}
      shell: bash
      if: ${{ inputs.gpg-key }} && ${{ inputs.gpg-fingerprint }} && ${{ inputs.gpg-passphrase }}
      env:
        GITHUB_USER: ${{ inputs.github-user }}
        GITHUB_TOKEN: ${{ inputs.github-user-token }}
