name: Container multi-arch image
description: Create a multi-arch image.

inputs:
  annotations:
    description: "New line seperated annotation list."
  digests:
    description: "New line seperated container image digest list."
    required: true
  tags:
    description: "New line seperated multi-arch tag list."
    required: true
  url:
    description: "Image url/name without registry."
    required: true
  registry:
    description: "Registry url."
    required: true
  registry-username:
    description: "Login registry username."
    required: true
  registry-password:
    description: "Login registry password."
    required: true

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Login to docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Create multi-arch image
      shell: bash
      run: |
        # Define the image URL
        url='${{ inputs.registry}}/${{ inputs.url }}'
        # Read tags and digests into arrays
        set +e
        IFS=$'\n' read -r -d '' -a tags <<< "$(printf '%s\n' '${{ inputs.tags }}' | sort -u)"
        IFS=$'\n' read -r -d '' -a digests <<< "$(printf '%s\n' '${{ inputs.digests }}' | sort -u)"
        IFS=$'\n' read -r -d '' -a annotations <<< "$(printf '%s\n' '${{ inputs.annotations }}' | sort -u)"
        set -e
        # Build the array of annotation args
        manifest_annotations=()
        for annotation in "${annotations[@]}"; do
          manifest_annotations+=('--annotation')
          manifest_annotations+=("$annotation")
        done
        # Build the array of tag args
        manifest_tags=()
        for tag in "${tags[@]}"; do
          manifest_tags+=('--tag')
          manifest_tags+=("$url:$tag")
        done
        # Build the array of image urls with digests
        manifest_images=()
        for digest in "${digests[@]}"; do
          manifest_images+=("$url@$digest")
        done
        docker buildx imagetools create ${manifest_annotations[@]} ${manifest_tags[@]} ${manifest_images[@]}
