name: "JavaScript/TypeScript Build & Test"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action to build and test Greenbone JavaScript/TypeScript Projects"
inputs:
  version:
    description: "Node version that should be installed"
    default: "16.x"
  token:
    description: "Token with GitHub Packages read rights required to install."
    required: true
    default: ${{ github.token }}
  dependency-manager:
    description: "What dependency manager should be used? [npm, yarn], default: npm"
    required: true
    default: "npm"
  registry-url:
    description: "npm registry to use for installing dependencies. default: 'https://npm.pkg.github.com'"
    default: "https://npm.pkg.github.com"
  report-file:
    description: "Create a coverage report. Report file default: report.xml"
    default: "report.xml"

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - run: echo "Install project with ${{ inputs.dependency-manager }}"
      shell: bash
    - name: Install Project
      uses: greenbone/actions/install-node@v3
      with:
        version: ${{ inputs.version }}
        token: ${{ inputs.token }}
        dependency-manager: ${{ inputs.dependency-manager }}
        registry-url: ${{ inputs.registry-url }}
    - name: Run Tests
      if: ${{ inputs.dependency-manager == 'npm' }}
      run: npm run test:ci
      shell: bash
    - name: Run Tests
      if: ${{ inputs.dependency-manager == 'yarn' }}
      run: yarn test:coverage --reporters=default
      env:
        JEST_JUNIT_OUTPUT_DIR: ${{ env.REPORT_DIR }}
      shell: bash
