name: "Lock branch action"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: "An action that locks the target branch and prevents pushing on it."

inputs:
  github-token:
    description: "Github user token, that is legitimated to set the lock."
    default: ${{ github.token }}
  lock:
    description: "Lock or unlock (Options: true, false)? Default: true"
    default: "true"
    required: true
  repository:
    description: "What repository branch should be locked? Defaults to the executing repository."
    default: ${{ github.repository }}
    required: true
  branch:
    description: "Branch that should be locked. Default: main"
    default: "main"
    required: true

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Set up Python and pontos
      uses: greenbone/actions/setup-pontos@v3
    - name: lock/unlock?
      run: |
        if [[ "${{inputs.lock}}" == "true" ]];
        then
          echo "LOCK_OPT=--lock" >> $GITHUB_ENV
        elif [[ "${{inputs.lock}}" == "false" ]];
        then
          echo "LOCK_OPT=--no-lock" >> $GITHUB_ENV
        else
          echo "LOCK_OPT=--no-lock" >> $GITHUB_ENV
        fi
      shell: bash
      # in case of blubber input let the branch be unlocked!
    - name: Prepare release and store the version
      run: |
        pontos-github-script pontos.github.scripts.lock-branch ${{ inputs.repository }} ${{ inputs.branch }} ${{ env.LOCK_OPT }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
