description: "Generate a depdenabot config for a repository with multiple actions."
name: "generate-dependabot-config"

runs:
  using: "composite"
  steps:
    - name: Refs
      run: |
        echo "::debug::ref: ${{ github.ref }}"
        echo "::debug::ref_name: ${{ github.ref_name }}"
        echo "::debug::head_ref: ${{ github.head_ref }}"
        echo "::debug::pr number: ${{ github.event.pull_request.number }}"
        echo "::debug::workspace: ${{ github.workspace }}"
        echo "::debug::action_path: ${{ github.action_path }}"
      shell: bash
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        path: "commit_dir"
        ref: ${{ github.head_ref }}
    - name: Set up Python and Poetry
      uses: greenbone/actions/poetry@v3
      with:
        working-directory: ${{ github.action_path }}
        cache-dependency-path: ${{ github.action_path }}/poetry.lock
        cache-poetry-installation: ${{ inputs.cache-poetry-installation }}
    - name: Run dependabot generator
      shell: bash
      # we start in the action directory because we want to execute this python code
      working-directory: ${{ github.action_path }}
      run: |
        config_file=.github/dependabot.yml
        # TODO: enable the python code to take the repository as parameter.
        # poetry run generate-dependabot-config ${{ github.workspace }}
        poetry run generate-dependabot-config

        echo copy config...
        cp ../${config_file} ${{ github.workspace }}/commit_dir/${config_file}

        echo changing to checked out dir
        cd ${{ github.workspace }}/commit_dir

        if [ -n "`git status --porcelain ${config_file}`" ]; then
          echo changed files
          git stash
          git pull --ff origin ${{ github.head_ref }}
          git stash pop
          git add .

          echo comitting
          git \
            -c user.name="${{ github.actor }}" \
            -c user.email="${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com" \
            commit \
            -m "[skip ci] Update dependabot config" \
            --author="${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>" \
            ${config_file}
        else
          echo nothing changed
        fi

        git log --max-count=3

        git push origin HEAD:${{ github.head_ref }}
