name: "Set ssh known hosts"
description: "Generate the ssh known hosts file"
inputs:
  known_hosts:
    description: "SSH known hosts text string"
    required: true
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: "Create ssh known hosts file"
      shell: bash
      run: |
        mkdir -p "$HOME/.ssh" || true
        chmod 0700 "$HOME/.ssh"
        echo -e "${{ inputs.known_hosts }}" > "$HOME/.ssh/known_hosts"
        chmod 0600 "$HOME/.ssh/known_hosts"
