name: "Action to set up the user for the workflow"
author: "Jaspar Stach <jaspar.stach@greenbone.net>"
description: |
  "An action that sets up the machines github user and email and "
  "activates the users tokens permissions to execute git commands."

# Never look up these commands again. :)

inputs:
  user:
    description: "GitHub user name on behalf of whom the actions will be executed. Default is 'github-actions'."
    default: github-actions
  mail:
    description: "Mail address for the given GitHub user. Default is 'github-actions@github.com'."
    default: github-actions@github.com
  token:
    description: "The GitHub user's token (PAT). Default is github.token."
    default: ${{ github.token }}
  repository:
    description: "GitHub repository to use. Default is github.repository."
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - run: echo "Setting up GitHub user and git permissions"
      shell: bash
    - name: Set git name, mail and origin
      run: |
        git config --global user.name "${{ inputs.user }}"
        git config --global user.email "${{ inputs.mail }}"
        git remote set-url origin https://${{ inputs.token }}@github.com/${{ inputs.repository }}
      shell: bash
