name: "Setup Pontos Action"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to setup python and pontos"

inputs:
  cache-key:
    description: "Key to use for the cache name."
    deprecationMessage: "cache-key is deprecated and will be ignored."
    default: "pontos-venv"
  python-version:
    description: "Python version that should be installed and used."
    default: "3.10"
  virtualenv-path:
    description: "Path to the created virtual environment"
    deprecationMessage: "virtualenv-path is deprecated and will be ignored."

outputs:
  virtualenv-path:
    description: "Path to the created virtual environment"
    value: ${{ steps.virtualenv.outputs.path }}
  activate:
    description: "Path to the activate environment script to source"
    value: ${{ steps.virtualenv.outputs.activate }}

branding:
  icon: "package"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Check if pontos is installed
      id: pontos
      run: command -v pontos > /dev/null && echo "installed=true" >> $GITHUB_OUTPUT || echo "installed=false" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install pontos via pipx
      id: pipx
      uses: greenbone/actions/pipx@62ad2c65d4d5e59b7e6608a4267a41c03ccb3cfd # v3.27.22
      with:
        python-version: ${{ steps.pontos.outputs.installed == 'false' && inputs.python-version || '' }}
        install: ${{  steps.pontos.outputs.installed == 'false' && 'pontos' || '' }}
        cache: "true"
    - name: Virtual Environment
      id: virtualenv
      run: |
        echo "path=${{ steps.pipx.outputs.venvs }}/pontos" >> $GITHUB_OUTPUT
        echo "activate=${{ steps.pipx.outputs.venvs }}/pontos/bin/activate" >> $GITHUB_OUTPUT
      shell: bash
    - name: Print pontos version
      run: |
        pontos --version
      shell: bash
