name: artifacts-download-trigger Build & Test

on:
  push:
    paths:
      - "artifacts-download-trigger/**"
  pull_request:
    paths:
      - "artifacts-download-trigger/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build the artifacts-download-trigger action"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "12"
      - name: Build with ncc
        run: |
          cd artifacts-download-trigger
          npm install -g yarn
          yarn install
          yarn run build
      - name: Archive dist
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: artifacts-download-trigger/dist
          retention-days: 1

  build-dist:
    needs:
      [
        build,
        timeout-test,
        failing-test,
        long-running-test,
        echo-2-test,
        echo-1-test,
      ]
    if: github.ref  && github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    name: "Commit dist of this action to the repo"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Commit dist file of this action
        run: |
          git config --global user.name "${{ secrets.GREENBONE_BOT }}"
          git config --global user.email "${{ secrets.GREENBONE_BOT_MAIL }}"
          git add artifacts-download-trigger/dist/index.js || true
          git commit -m "New build of artifacts-download-trigger/dist/index.js" || true
          remote_repo="https://${GITHUB_ACTOR}:${{secrets.GREENBONE_BOT_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:${GITHUB_REF} || true
