name: artifacts-download-trigger Build & Test

on:
  push:
    branches: [ main, 'feature/*' ]
    paths:
      - 'artifacts-download-trigger/**'
  pull_request:
    branches: [ main, 'feature/*' ]
    paths:
      - 'artifacts-download-trigger/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build with ncc
        run: |
          cd artifacts-download-trigger
          npm install -g yarn
          yarn install
          yarn run build
      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist

  echo-1-test:
    needs: [build]
    runs-on: ubuntu-latest
    name: "echo-1-test [trigger|by workflow name]"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Invoke echo 1 workflow using this action (do not wait for completion)
        uses: ./artifacts-download-trigger
        with:
          workflow: Message Echo 1
          gh_token: ${{ secrets.BOT_PAT_TOKEN }}
          inputs: '{"message": "blah blah"}'
          wait-for-completion: false

  echo-2-test:
    needs: [build]
    runs-on: ubuntu-latest
    name: "echo-2-test [trigger|by workflow filename]"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Invoke echo 2 workflow using this action
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-echo-2.yaml
          gh_token: ${{ secrets.BOT_PAT_TOKEN }}
          wait-for-completion: false

    # - name: Invoke echo 1 workflow by id
    #   uses: ./
    #   with:
    #     workflow: '1854247'
    #     token: ${{ secrets.PERSONAL_TOKEN }}
    #     inputs: '{"message": "Mango jam"}'
    #     wait-for-completion: false

  long-running-test:
    needs: [build]
    runs-on: ubuntu-latest
    name: "long-running-test [trigger+wait|by workflow filename|shoud succeed]"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Invoke 'long-running' workflow and wait for result using this action
        id: long-running-workflow
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-long-running.yml
          gh_token: ${{ secrets.BOT_PAT_TOKEN }}
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 5m
        continue-on-error: true
      - uses: nick-invision/assert-action@v1
        with:
          expected: success
          actual: ${{ steps.long-running-workflow.outputs.workflow-conclusion }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: success
          actual: ${{ steps.long-running-workflow.outcome }}

  failing-test:
    needs: [build]
    runs-on: ubuntu-latest
    name: "failing-test [trigger+wait|by workflow filename|should report failure]"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Invoke 'failing' workflow and wait for result using this action
        id: failing-workflow
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-failing.yml
          gh_token: ${{ secrets.BOT_PAT_TOKEN }}
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 5m
        continue-on-error: true
      - run: echo "worflow-conclusion=${{ steps.failing-workflow.outputs.workflow-conclusion }}"
      - uses: nick-invision/assert-action@v1
        with:
          expected: failure
          actual: ${{ steps.failing-workflow.outputs.workflow-conclusion }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: failure
          actual: ${{ steps.failing-workflow.outcome }}

  timeout-test:
    needs: [build]
    runs-on: ubuntu-latest
    name: "timeout-test [trigger+wait|by workflow filename|shoud report timed_out]"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Invoke 'timeout' workflow and wait for result using this action
        id: timeout-workflow
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-timeout.yml
          gh_token: ${{ secrets.BOT_PAT_TOKEN }}
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 30s
        continue-on-error: true
      - uses: nick-invision/assert-action@v1
        with:
          expected: timed_out
          actual: ${{ steps.timeout-workflow.outputs.workflow-conclusion }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: failure
          actual: ${{ steps.timeout-workflow.outcome }}

    # - name: Invoke external workflow using this action
    #   uses: ./
    #   with:
    #     workflow: Deploy To Kubernetes
    #     repo: benc-uk/dapr-store
    #     token: ${{ secrets.PERSONAL_TOKEN }}
    #     ref: master

  deploy:
    needs: [echo-1-test, echo-2-test, long-running-test, failing-test, timeout-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: build
          path: artifacts-download-trigger/dist
      - name: Update repo with build
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_gh_token: ${{ secrets.BOT_PAT_TOKEN }}