name: Auto-merge sqash

on: pull_request_target
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
    
jobs:
  auto-merge:
    uses: greenbone/workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit
