name: Backport Action Container Image Builds

on:
  push:
    branches: [main, "v*"]
    # only run if a file in backport-pull-request has changed
    paths:
      - "backport-pull-request/**"
      - ".github/workflows/backport-action-container.yml"
    tags: ["v*"]
  workflow_dispatch:

jobs:
  images:
    name: Build backport-pull-request image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup container meta information
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: greenbone/backport-pull-request
          labels: |
            org.opencontainers.image.vendor=Greenbone
            org.opencontainers.image.base.name=debian/stable-slim
          flavor: latest=false # no latest container tag for git tags
          tags: |
            # create container tag for git tags
            type=ref,event=tag
            type=ref,event=pr
            type=ref,event=branch
      - name: Build and push Container image
        uses: docker/build-push-action@v3
        with:
          context: backport-pull-request
          push: ${{ github.event_name != 'pull_request' }}
          file: backport-pull-request/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
