name: Download Artifact Action Container Image Builds

on:
  push:
    branches:
      - main
      - "v*"
    paths:
      - "download-artifact/**"
      - ".github/workflows/download-artifact-action-container.yml"
    tags: ["v*"]
  pull_request:
    paths:
      - "download-artifact/**"
      - ".github/workflows/download-artifact-action-container.yml"
  workflow_dispatch:

jobs:
  images:
    name: Build download-artifact-action image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup container meta information
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/greenbone/download-artifact-action
          labels: |
            org.opencontainers.image.vendor=Greenbone
            org.opencontainers.image.base.name=python:3.9-slim
          flavor: latest=false # no latest container tag for git tags
          tags: |
            # create container tag for git tags
            type=ref,event=tag
            type=ref,event=pr
            type=ref,event=branch
      - name: Build and push Container image
        uses: docker/build-push-action@v3
        with:
          context: download-artifact
          push: ${{ github.event_name != 'pull_request' }}
          file: download-artifact/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
