name: Trigger release of a new action
# We will push the action to the correct branch
# and can use it afterwards with the `@v2` tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: | 
          Enter the version for the release tag.
          Must be larger than last tag.
          Use patch (0.0.x) for bug fixes.
          Use minor (0.x.0) for new actions.
        type: string
        required: true
      branch:
        description: |
          Specify the branch to push to.
          Default will be `v2`
        type: string
        default: v2

jobs:
  merge-to-v1-branch:
    name: Create release by rebasing main to ${{ github.event.inputs.branch }} and create a new tag
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set git name, mail and origin
        run: |
          git config --global user.name "${{ secrets.GREENBONE_BOT }}"
          git config --global user.email "${{ secrets.GREENBONE_BOT_MAIL }}"
      - name: Checkout ${{ github.event.inputs.branch }} branch and merge
        run: |
          git checkout ${{ github.event.inputs.branch }}
          git merge main -m "Merge main into ${{ github.event.inputs.branch }} for the new tag v${{ github.event.inputs.tag }}"
      - name: Generate new tag, push tag and branch
        run: |
          git tag v${{ github.event.inputs.tag }}
          git push
          git push --tags
