name: To Be Triggered Failing Test Workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
