name: To be Triggered Test Workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 60s
