name: Test Release Actions

on:
  push:
    tags:
      - "v*"
    branches:
      - main
    paths:
      - "release/**"
      - "release-python/**"
      - ".github/workflows/test-release.yml"
  pull_request:
    branches:
      - main
    paths:
      - "release/**"
      - "release-python/**"
      - ".github/workflows/test-release.yml"

jobs:
  release-patch-cc:
    runs-on: ubuntu-latest
    name: Test Release Patch CC
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run release patch actions
        uses: ./release
        with:
          github-user: foo
          github-user-mail: foo@bar.baz
          github-user-token: bar
          gpg-key: boo
          gpg-passphrase: foo
          gpg-fingerprint: baz
        continue-on-error: true
  release-patch:
    runs-on: ubuntu-latest
    name: Test Release Calendar changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run release patch actions
        uses: ./release-python
        with:
          github-user: ${{ secrets.GREENBONE_BOT }}
          github-user-mail: foo@bar.baz
          github-user-token: bar
          gpg-key: boo
          gpg-passphrase: foo
          gpg-fingerprint: baz
          conventional-commits: false
          strategy: calendar
          ref: v1
        continue-on-error: true
